theme: jekyll-theme-minimal
title: Robert Thiesmeier
description: Welcome to my personal website. Here you can find some recent publications, presentations and talks, and blog entries to specific topics that I am interested in.

